import { UserRole } from "@prisma/client";
import { Pill, Contact, Stethoscope, ScrollText, FolderClosed, Home, Settings, Upload } from "lucide-react";

export const navRoutes = [
  {
    icon: Home,
    href: "/patient-home",
    label: "Home",
  },
  {
    icon: FolderClosed,
    href: "/files",
    label: "Files",
  },
  {
    icon: Pill,
    href: "/medications",
    label: "Meds",
  },
  {
    icon: Contact,
    href: "/about",
    label: "About",
  },
  // {
  //   icon: ScrollText,
  //   href: "/notes",
  //   label: "Notes",
  // },
  {
    icon: Stethoscope,
    href: "/providers",
    label: "Providers",
  },
  {
    icon: Settings,
    href: "/patient-settings",
    label: "Settings",
  },
];

export const tempPatientAccessNavRoutes = [
  {
    icon: Home,
    href: "/tpa-home",
    label: "Home",
  },
  {
    icon: FolderClosed,
    href: "/tpa-files",
    label: "Files",
  },
  {
    icon: Pill,
    href: "/tpa-medications",
    label: "Meds",
  },
  {
    icon: Contact,
    href: "/tpa-about",
    label: "About",
  },
];

export const tempPatientUploadAccessNavRoutes = [
  {
    icon: Home,
    href: "/tpa-home",
    label: "Home",
  },
  {
    icon: Upload,
    href: "/tpa-upload",
    label: "Upload",
  },
];

export interface SelectItemType {
  value: string;
  value2?: string;
  label: string;
}

export interface SimpleSelectItemsType {
  height: SelectItemType[];
  weight: SelectItemType[];
}
interface AccessType {
  title: string;
  description: string;
}

export interface AccessTypeObjectType {
  [key: string]: AccessType;
}

export const accessTypeTextObjForPatient: AccessTypeObjectType = {
  READ_ONLY: { title: "Read Only", description: "can only view records and are unable to make changes of any kind" },
  UPLOAD_FILES_ONLY: {
    title: "Upload Files Only",
    description: "can only upload files to a folder of your choosing. Your records will be hidden",
  },
  READ_AND_ADD: {
    title: "Read & Add",
    description: "can view records and add records i.e. medications & folders/files",
  },
  FULL_ACCESS: {
    title: "Full Access",
    description:
      "can view records, add records i.e. medications & folders/files, make edits to existing medications, and rename & move folders/files",
  },
};

export const accessTypeTextObjForTemp: AccessTypeObjectType = {
  READ_ONLY: { title: "Read Only", description: "can only view records and are unable to make changes of any kind" },
  UPLOAD_FILES_ONLY: {
    title: "Upload Files Only",
    description:
      "can only upload files. A destination folder has already been selected by the patient. You do not have access to any of the patient's records",
  },
  READ_AND_ADD: {
    title: "Read & Add",
    description: "can view records and add records i.e. medications & folders/files",
  },
  FULL_ACCESS: {
    title: "Full Access",
    description:
      "can view records, add records i.e. medications & folders/files, make edits to existing medications, and rename & move folders/files",
  },
};

export const simpleSelectItems: SimpleSelectItemsType = {
  height: [
    { value: "FT", label: "Ft" },
    { value: "CM", label: "Cm" },
  ],
  weight: [
    { value: "KG", label: "Kg" },
    { value: "LBS", label: "LBS" },
  ],
};

export const genders = [
  { value: "MALE", label: "Male" },
  { value: "FEMALE", label: "Female" },
];

export const races = [
  { value: "ASIAN", label: "Asian" },
  { value: "BLACK", label: "Black or African American" },
  { value: "NATIVE", label: "Native American" },
  { value: "ISLANDER", label: "Pacific Islander" },
  { value: "WHITE", label: "White" },
];

export const martialStatuses = [
  { value: "SINGLE", label: "Single" },
  { value: "MARRIED", label: "Married" },
  { value: "DIVORCED", label: "Divorced" },
  { value: "WIDOWED", label: "Widowed" },
  { value: "SEPARATED", label: "Separated" },
];

export const heightsImperial = [
  { value: "1' 0\"", label: "1' 0\"" },
  { value: "1' 1\"", label: "1' 1\"" },
  { value: "1' 2\"", label: "1' 2\"" },
  { value: "1' 3\"", label: "1' 3\"" },
  { value: "1' 4\"", label: "1' 4\"" },
  { value: "1' 5\"", label: "1' 5\"" },
  { value: "1' 6\"", label: "1' 6\"" },
  { value: "1' 7\"", label: "1' 7\"" },
  { value: "1' 8\"", label: "1' 8\"" },
  { value: "1' 9\"", label: "1' 9\"" },
  { value: "1' 10\"", label: "1' 10\"" },
  { value: "1' 11\"", label: "1' 11\"" },
  { value: "2' 0\"", label: "2' 0\"" },
  { value: "2' 1\"", label: "2' 1\"" },
  { value: "2' 2\"", label: "2' 2\"" },
  { value: "2' 3\"", label: "2' 3\"" },
  { value: "2' 4\"", label: "2' 4\"" },
  { value: "2' 5\"", label: "2' 5\"" },
  { value: "2' 6\"", label: "2' 6\"" },
  { value: "2' 7\"", label: "2' 7\"" },
  { value: "2' 8\"", label: "2' 8\"" },
  { value: "2' 9\"", label: "2' 9\"" },
  { value: "2' 10\"", label: "2' 10\"" },
  { value: "2' 11\"", label: "2' 11\"" },
  { value: "3' 0\"", label: "3' 0\"" },
  { value: "3' 1\"", label: "3' 1\"" },
  { value: "3' 2\"", label: "3' 2\"" },
  { value: "3' 3\"", label: "3' 3\"" },
  { value: "3' 4\"", label: "3' 4\"" },
  { value: "3' 5\"", label: "3' 5\"" },
  { value: "3' 6\"", label: "3' 6\"" },
  { value: "3' 7\"", label: "3' 7\"" },
  { value: "3' 8\"", label: "3' 8\"" },
  { value: "3' 9\"", label: "3' 9\"" },
  { value: "3' 10\"", label: "3' 10\"" },
  { value: "3' 11\"", label: "3' 11\"" },
  { value: "4' 0\"", label: "4' 0\"" },
  { value: "4' 1\"", label: "4' 1\"" },
  { value: "4' 2\"", label: "4' 2\"" },
  { value: "4' 3\"", label: "4' 3\"" },
  { value: "4' 4\"", label: "4' 4\"" },
  { value: "4' 5\"", label: "4' 5\"" },
  { value: "4' 6\"", label: "4' 6\"" },
  { value: "4' 7\"", label: "4' 7\"" },
  { value: "4' 8\"", label: "4' 8\"" },
  { value: "4' 9\"", label: "4' 9\"" },
  { value: "4' 10\"", label: "4' 10\"" },
  { value: "4' 11\"", label: "4' 11\"" },
  { value: "5' 0\"", label: "5' 0\"" },
  { value: "5' 1\"", label: "5' 1\"" },
  { value: "5' 2\"", label: "5' 2\"" },
  { value: "5' 3\"", label: "5' 3\"" },
  { value: "5' 4\"", label: "5' 4\"" },
  { value: "5' 5\"", label: "5' 5\"" },
  { value: "5' 6\"", label: "5' 6\"" },
  { value: "5' 7\"", label: "5' 7\"" },
  { value: "5' 8\"", label: "5' 8\"" },
  { value: "5' 9\"", label: "5' 9\"" },
  { value: "5' 10\"", label: "5' 10\"" },
  { value: "5' 11\"", label: "5' 11\"" },
  { value: "6' 0\"", label: "6' 0\"" },
  { value: "6' 1\"", label: "6' 1\"" },
  { value: "6' 2\"", label: "6' 2\"" },
  { value: "6' 3\"", label: "6' 3\"" },
  { value: "6' 4\"", label: "6' 4\"" },
  { value: "6' 5\"", label: "6' 5\"" },
  { value: "6' 6\"", label: "6' 6\"" },
  { value: "6' 7\"", label: "6' 7\"" },
  { value: "6' 8\"", label: "6' 8\"" },
  { value: "6' 9\"", label: "6' 9\"" },
  { value: "6' 10\"", label: "6' 10\"" },
  { value: "6' 11\"", label: "6' 11\"" },
  { value: "7' 0\"", label: "7' 0\"" },
  { value: "7' 1\"", label: "7' 1\"" },
  { value: "7' 2\"", label: "7' 2\"" },
  { value: "7' 3\"", label: "7' 3\"" },
  { value: "7' 4\"", label: "7' 4\"" },
  { value: "7' 5\"", label: "7' 5\"" },
  { value: "7' 6\"", label: "7' 6\"" },
  { value: "7' 7\"", label: "7' 7\"" },
  { value: "7' 8\"", label: "7' 8\"" },
  { value: "7' 9\"", label: "7' 9\"" },
  { value: "7' 10\"", label: "7' 10\"" },
  { value: "7' 11\"", label: "7' 11\"" },
  { value: "8' 0\"", label: "8' 0\"" },
  { value: "8' 1\"", label: "8' 1\"" },
  { value: "8' 2\"", label: "8' 2\"" },
  { value: "8' 3\"", label: "8' 3\"" },
  { value: "8' 4\"", label: "8' 4\"" },
  { value: "8' 5\"", label: "8' 5\"" },
  { value: "8' 6\"", label: "8' 6\"" },
  { value: "8' 7\"", label: "8' 7\"" },
  { value: "8' 8\"", label: "8' 8\"" },
  { value: "8' 9\"", label: "8' 9\"" },
  { value: "8' 10\"", label: "8' 10\"" },
  { value: "8' 11\"", label: "8' 11\"" },
  { value: "9' 0\"", label: "9' 0\"" },
  { value: "9' 1\"", label: "9' 1\"" },
  { value: "9' 2\"", label: "9' 2\"" },
  { value: "9' 3\"", label: "9' 3\"" },
  { value: "9' 4\"", label: "9' 4\"" },
  { value: "9' 5\"", label: "9' 5\"" },
  { value: "9' 6\"", label: "9' 6\"" },
  { value: "9' 7\"", label: "9' 7\"" },
  { value: "9' 8\"", label: "9' 8\"" },
  { value: "9' 9\"", label: "9' 9\"" },
  { value: "9' 10\"", label: "9' 10\"" },
  { value: "9' 11\"", label: "9' 11\"" },
  { value: "10' 0\"", label: "10' 0\"" },
  { value: "10' 1\"", label: "10' 1\"" },
  { value: "10' 2\"", label: "10' 2\"" },
  { value: "10' 3\"", label: "10' 3\"" },
  { value: "10' 4\"", label: "10' 4\"" },
  { value: "10' 5\"", label: "10' 5\"" },
  { value: "10' 6\"", label: "10' 6\"" },
  { value: "10' 7\"", label: "10' 7\"" },
  { value: "10' 8\"", label: "10' 8\"" },
  { value: "10' 9\"", label: "10' 9\"" },
  { value: "10' 10\"", label: "10' 10\"" },
  { value: "10' 11\"", label: "10' 11\"" },
];

export const heightsMetric = [
  { value: "30 cm", label: "30 cm" },
  { value: "31 cm", label: "31 cm" },
  { value: "32 cm", label: "32 cm" },
  { value: "33 cm", label: "33 cm" },
  { value: "34 cm", label: "34 cm" },
  { value: "35 cm", label: "35 cm" },
  { value: "36 cm", label: "36 cm" },
  { value: "37 cm", label: "37 cm" },
  { value: "38 cm", label: "38 cm" },
  { value: "39 cm", label: "39 cm" },
  { value: "40 cm", label: "40 cm" },
  { value: "41 cm", label: "41 cm" },
  { value: "42 cm", label: "42 cm" },
  { value: "43 cm", label: "43 cm" },
  { value: "44 cm", label: "44 cm" },
  { value: "45 cm", label: "45 cm" },
  { value: "46 cm", label: "46 cm" },
  { value: "47 cm", label: "47 cm" },
  { value: "48 cm", label: "48 cm" },
  { value: "49 cm", label: "49 cm" },
  { value: "50 cm", label: "50 cm" },
  { value: "51 cm", label: "51 cm" },
  { value: "52 cm", label: "52 cm" },
  { value: "53 cm", label: "53 cm" },
  { value: "54 cm", label: "54 cm" },
  { value: "55 cm", label: "55 cm" },
  { value: "56 cm", label: "56 cm" },
  { value: "57 cm", label: "57 cm" },
  { value: "58 cm", label: "58 cm" },
  { value: "59 cm", label: "59 cm" },
  { value: "60 cm", label: "60 cm" },
  { value: "61 cm", label: "61 cm" },
  { value: "62 cm", label: "62 cm" },
  { value: "63 cm", label: "63 cm" },
  { value: "64 cm", label: "64 cm" },
  { value: "65 cm", label: "65 cm" },
  { value: "66 cm", label: "66 cm" },
  { value: "67 cm", label: "67 cm" },
  { value: "68 cm", label: "68 cm" },
  { value: "69 cm", label: "69 cm" },
  { value: "70 cm", label: "70 cm" },
  { value: "71 cm", label: "71 cm" },
  { value: "72 cm", label: "72 cm" },
  { value: "73 cm", label: "73 cm" },
  { value: "74 cm", label: "74 cm" },
  { value: "75 cm", label: "75 cm" },
  { value: "76 cm", label: "76 cm" },
  { value: "77 cm", label: "77 cm" },
  { value: "78 cm", label: "78 cm" },
  { value: "79 cm", label: "79 cm" },
  { value: "80 cm", label: "80 cm" },
  { value: "81 cm", label: "81 cm" },
  { value: "82 cm", label: "82 cm" },
  { value: "83 cm", label: "83 cm" },
  { value: "84 cm", label: "84 cm" },
  { value: "85 cm", label: "85 cm" },
  { value: "86 cm", label: "86 cm" },
  { value: "87 cm", label: "87 cm" },
  { value: "88 cm", label: "88 cm" },
  { value: "89 cm", label: "89 cm" },
  { value: "90 cm", label: "90 cm" },
  { value: "91 cm", label: "91 cm" },
  { value: "92 cm", label: "92 cm" },
  { value: "93 cm", label: "93 cm" },
  { value: "94 cm", label: "94 cm" },
  { value: "95 cm", label: "95 cm" },
  { value: "96 cm", label: "96 cm" },
  { value: "97 cm", label: "97 cm" },
  { value: "98 cm", label: "98 cm" },
  { value: "99 cm", label: "99 cm" },
  { value: "100 cm", label: "100 cm" },
  { value: "101 cm", label: "101 cm" },
  { value: "102 cm", label: "102 cm" },
  { value: "103 cm", label: "103 cm" },
  { value: "104 cm", label: "104 cm" },
  { value: "105 cm", label: "105 cm" },
  { value: "106 cm", label: "106 cm" },
  { value: "107 cm", label: "107 cm" },
  { value: "108 cm", label: "108 cm" },
  { value: "109 cm", label: "109 cm" },
  { value: "110 cm", label: "110 cm" },
  { value: "111 cm", label: "111 cm" },
  { value: "112 cm", label: "112 cm" },
  { value: "113 cm", label: "113 cm" },
  { value: "114 cm", label: "114 cm" },
  { value: "115 cm", label: "115 cm" },
  { value: "116 cm", label: "116 cm" },
  { value: "117 cm", label: "117 cm" },
  { value: "118 cm", label: "118 cm" },
  { value: "119 cm", label: "119 cm" },
  { value: "120 cm", label: "120 cm" },
  { value: "121 cm", label: "121 cm" },
  { value: "122 cm", label: "122 cm" },
  { value: "123 cm", label: "123 cm" },
  { value: "124 cm", label: "124 cm" },
  { value: "125 cm", label: "125 cm" },
  { value: "126 cm", label: "126 cm" },
  { value: "127 cm", label: "127 cm" },
  { value: "128 cm", label: "128 cm" },
  { value: "129 cm", label: "129 cm" },
  { value: "130 cm", label: "130 cm" },
  { value: "131 cm", label: "131 cm" },
  { value: "132 cm", label: "132 cm" },
  { value: "133 cm", label: "133 cm" },
  { value: "134 cm", label: "134 cm" },
  { value: "135 cm", label: "135 cm" },
  { value: "136 cm", label: "136 cm" },
  { value: "137 cm", label: "137 cm" },
  { value: "138 cm", label: "138 cm" },
  { value: "139 cm", label: "139 cm" },
  { value: "140 cm", label: "140 cm" },
  { value: "141 cm", label: "141 cm" },
  { value: "142 cm", label: "142 cm" },
  { value: "143 cm", label: "143 cm" },
  { value: "144 cm", label: "144 cm" },
  { value: "145 cm", label: "145 cm" },
  { value: "146 cm", label: "146 cm" },
  { value: "147 cm", label: "147 cm" },
  { value: "148 cm", label: "148 cm" },
  { value: "149 cm", label: "149 cm" },
  { value: "150 cm", label: "150 cm" },
  { value: "151 cm", label: "151 cm" },
  { value: "152 cm", label: "152 cm" },
  { value: "153 cm", label: "153 cm" },
  { value: "154 cm", label: "154 cm" },
  { value: "155 cm", label: "155 cm" },
  { value: "156 cm", label: "156 cm" },
  { value: "157 cm", label: "157 cm" },
  { value: "158 cm", label: "158 cm" },
  { value: "159 cm", label: "159 cm" },
  { value: "160 cm", label: "160 cm" },
  { value: "161 cm", label: "161 cm" },
  { value: "162 cm", label: "162 cm" },
  { value: "163 cm", label: "163 cm" },
  { value: "164 cm", label: "164 cm" },
  { value: "165 cm", label: "165 cm" },
  { value: "166 cm", label: "166 cm" },
  { value: "167 cm", label: "167 cm" },
  { value: "168 cm", label: "168 cm" },
  { value: "169 cm", label: "169 cm" },
  { value: "170 cm", label: "170 cm" },
  { value: "171 cm", label: "171 cm" },
  { value: "172 cm", label: "172 cm" },
  { value: "173 cm", label: "173 cm" },
  { value: "174 cm", label: "174 cm" },
  { value: "175 cm", label: "175 cm" },
  { value: "176 cm", label: "176 cm" },
  { value: "177 cm", label: "177 cm" },
  { value: "178 cm", label: "178 cm" },
  { value: "179 cm", label: "179 cm" },
  { value: "180 cm", label: "180 cm" },
  { value: "181 cm", label: "181 cm" },
  { value: "182 cm", label: "182 cm" },
  { value: "183 cm", label: "183 cm" },
  { value: "184 cm", label: "184 cm" },
  { value: "185 cm", label: "185 cm" },
  { value: "186 cm", label: "186 cm" },
  { value: "187 cm", label: "187 cm" },
  { value: "188 cm", label: "188 cm" },
  { value: "189 cm", label: "189 cm" },
  { value: "190 cm", label: "190 cm" },
  { value: "191 cm", label: "191 cm" },
  { value: "192 cm", label: "192 cm" },
  { value: "193 cm", label: "193 cm" },
  { value: "194 cm", label: "194 cm" },
  { value: "195 cm", label: "195 cm" },
  { value: "196 cm", label: "196 cm" },
  { value: "197 cm", label: "197 cm" },
  { value: "198 cm", label: "198 cm" },
  { value: "199 cm", label: "199 cm" },
  { value: "200 cm", label: "200 cm" },
  { value: "201 cm", label: "201 cm" },
  { value: "202 cm", label: "202 cm" },
  { value: "203 cm", label: "203 cm" },
  { value: "204 cm", label: "204 cm" },
  { value: "205 cm", label: "205 cm" },
  { value: "206 cm", label: "206 cm" },
  { value: "207 cm", label: "207 cm" },
  { value: "208 cm", label: "208 cm" },
  { value: "209 cm", label: "209 cm" },
  { value: "210 cm", label: "210 cm" },
  { value: "211 cm", label: "211 cm" },
  { value: "212 cm", label: "212 cm" },
  { value: "213 cm", label: "213 cm" },
  { value: "214 cm", label: "214 cm" },
  { value: "215 cm", label: "215 cm" },
  { value: "216 cm", label: "216 cm" },
  { value: "217 cm", label: "217 cm" },
  { value: "218 cm", label: "218 cm" },
  { value: "219 cm", label: "219 cm" },
  { value: "220 cm", label: "220 cm" },
  { value: "221 cm", label: "221 cm" },
  { value: "222 cm", label: "222 cm" },
  { value: "223 cm", label: "223 cm" },
  { value: "224 cm", label: "224 cm" },
  { value: "225 cm", label: "225 cm" },
  { value: "226 cm", label: "226 cm" },
  { value: "227 cm", label: "227 cm" },
  { value: "228 cm", label: "228 cm" },
  { value: "229 cm", label: "229 cm" },
  { value: "230 cm", label: "230 cm" },
  { value: "231 cm", label: "231 cm" },
  { value: "232 cm", label: "232 cm" },
  { value: "233 cm", label: "233 cm" },
  { value: "234 cm", label: "234 cm" },
  { value: "235 cm", label: "235 cm" },
  { value: "236 cm", label: "236 cm" },
  { value: "237 cm", label: "237 cm" },
  { value: "238 cm", label: "238 cm" },
  { value: "239 cm", label: "239 cm" },
  { value: "240 cm", label: "240 cm" },
  { value: "241 cm", label: "241 cm" },
  { value: "242 cm", label: "242 cm" },
  { value: "243 cm", label: "243 cm" },
  { value: "244 cm", label: "244 cm" },
  { value: "245 cm", label: "245 cm" },
  { value: "246 cm", label: "246 cm" },
  { value: "247 cm", label: "247 cm" },
  { value: "248 cm", label: "248 cm" },
  { value: "249 cm", label: "249 cm" },
  { value: "250 cm", label: "250 cm" },
  { value: "251 cm", label: "251 cm" },
  { value: "252 cm", label: "252 cm" },
  { value: "253 cm", label: "253 cm" },
  { value: "254 cm", label: "254 cm" },
  { value: "255 cm", label: "255 cm" },
  { value: "256 cm", label: "256 cm" },
  { value: "257 cm", label: "257 cm" },
  { value: "258 cm", label: "258 cm" },
  { value: "259 cm", label: "259 cm" },
  { value: "260 cm", label: "260 cm" },
  { value: "261 cm", label: "261 cm" },
  { value: "262 cm", label: "262 cm" },
  { value: "263 cm", label: "263 cm" },
  { value: "264 cm", label: "264 cm" },
  { value: "265 cm", label: "265 cm" },
  { value: "266 cm", label: "266 cm" },
  { value: "267 cm", label: "267 cm" },
  { value: "268 cm", label: "268 cm" },
  { value: "269 cm", label: "269 cm" },
  { value: "270 cm", label: "270 cm" },
  { value: "271 cm", label: "271 cm" },
  { value: "272 cm", label: "272 cm" },
  { value: "273 cm", label: "273 cm" },
  { value: "274 cm", label: "274 cm" },
  { value: "275 cm", label: "275 cm" },
  { value: "276 cm", label: "276 cm" },
  { value: "277 cm", label: "277 cm" },
  { value: "278 cm", label: "278 cm" },
  { value: "279 cm", label: "279 cm" },
  { value: "280 cm", label: "280 cm" },
  { value: "281 cm", label: "281 cm" },
  { value: "282 cm", label: "282 cm" },
  { value: "283 cm", label: "283 cm" },
  { value: "284 cm", label: "284 cm" },
  { value: "285 cm", label: "285 cm" },
  { value: "286 cm", label: "286 cm" },
  { value: "287 cm", label: "287 cm" },
  { value: "288 cm", label: "288 cm" },
  { value: "289 cm", label: "289 cm" },
  { value: "290 cm", label: "290 cm" },
  { value: "291 cm", label: "291 cm" },
  { value: "292 cm", label: "292 cm" },
  { value: "293 cm", label: "293 cm" },
  { value: "294 cm", label: "294 cm" },
  { value: "295 cm", label: "295 cm" },
  { value: "296 cm", label: "296 cm" },
  { value: "297 cm", label: "297 cm" },
  { value: "298 cm", label: "298 cm" },
  { value: "299 cm", label: "299 cm" },
  { value: "300 cm", label: "300 cm" },
  { value: "301 cm", label: "301 cm" },
  { value: "302 cm", label: "302 cm" },
  { value: "303 cm", label: "303 cm" },
  { value: "304 cm", label: "304 cm" },
  { value: "305 cm", label: "305 cm" },
  { value: "306 cm", label: "306 cm" },
  { value: "307 cm", label: "307 cm" },
  { value: "308 cm", label: "308 cm" },
];

export const states = [
  { value: "AL", label: "AL" },
  { value: "AK", label: "AK" },
  { value: "AZ", label: "AZ" },
  { value: "AR", label: "AR" },
  { value: "CA", label: "CA" },
  { value: "CO", label: "CO" },
  { value: "CT", label: "CT" },
  { value: "DE", label: "DE" },
  { value: "FL", label: "FL" },
  { value: "GA", label: "GA" },
  { value: "HI", label: "HI" },
  { value: "ID", label: "ID" },
  { value: "IL", label: "IL" },
  { value: "IN", label: "IN" },
  { value: "IA", label: "IA" },
  { value: "KS", label: "KS" },
  { value: "KY", label: "KY" },
  { value: "LA", label: "LA" },
  { value: "ME", label: "ME" },
  { value: "MD", label: "MD" },
  { value: "MA", label: "MA" },
  { value: "MI", label: "MI" },
  { value: "MN", label: "MN" },
  { value: "MS", label: "MS" },
  { value: "MO", label: "MO" },
  { value: "MT", label: "MT" },
  { value: "NE", label: "NE" },
  { value: "NV", label: "NV" },
  { value: "NH", label: "NH" },
  { value: "NJ", label: "NJ" },
  { value: "NM", label: "NM" },
  { value: "NY", label: "NY" },
  { value: "NC", label: "NC" },
  { value: "ND", label: "ND" },
  { value: "OH", label: "OH" },
  { value: "OK", label: "OK" },
  { value: "OR", label: "OR" },
  { value: "PA", label: "PA" },
  { value: "RI", label: "RI" },
  { value: "SC", label: "SC" },
  { value: "SD", label: "SD" },
  { value: "TN", label: "TN" },
  { value: "TX", label: "TX" },
  { value: "UT", label: "UT" },
  { value: "VT", label: "VT" },
  { value: "VA", label: "VA" },
  { value: "WA", label: "WA" },
  { value: "WV", label: "WV" },
  { value: "WI", label: "WI" },
  { value: "WY", label: "WY" },
];

export const medicationCategories = [
  { value: "Allergy", label: "Allergy" },
  { value: "Cardiology", label: "Cardiology" },
  { value: "Dermatology", label: "Dermatology" },
  { value: "Endocrinology", label: "Endocrinology" },
  { value: "Gastroenterology", label: "Gastroenterology" },
  { value: "Hematology", label: "Hematology" },
  { value: "Immunology", label: "Immunology" },
  { value: "Infectious Diseases", label: "Infectious Diseases" },
  { value: "Nephrology", label: "Nephrology" },
  { value: "Neurology", label: "Neurology" },
  { value: "Oncology", label: "Oncology" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "Orthopedics", label: "Orthopedics" },
  { value: "Pediatrics", label: "Pediatrics" },
  { value: "Psychiatry", label: "Psychiatry" },
  { value: "Pulmonology", label: "Pulmonology" },
  { value: "Rheumatology", label: "Rheumatology" },
  { value: "Urology", label: "Urology" },
];

export const rootFolderCategories = [
  { value: "Allergy", label: "Allergy" },
  { value: "Cardiology", label: "Cardiology" },
  { value: "Dermatology", label: "Dermatology" },
  { value: "Endocrinology", label: "Endocrinology" },
  { value: "Gastroenterology", label: "Gastroenterology" },
  { value: "Hematology", label: "Hematology" },
  { value: "Immunology", label: "Immunology" },
  { value: "Infectious Diseases", label: "Infectious Diseases" },
  { value: "Nephrology", label: "Nephrology" },
  { value: "Neurology", label: "Neurology" },
  { value: "Oncology", label: "Oncology" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "Orthopedics", label: "Orthopedics" },
  { value: "Pediatrics", label: "Pediatrics" },
  { value: "Psychiatry", label: "Psychiatry" },
  { value: "Pulmonology", label: "Pulmonology" },
  { value: "Rheumatology", label: "Rheumatology" },
  { value: "Urology", label: "Urology" },
];

export const medicationsList = [
  { value: "Abacavir", label: "Abacavir" },
  { value: "Abatacept", label: "Abatacept" },
  { value: "Abemaciclib", label: "Abemaciclib" },
  { value: "Abilify (Aripiprazole)", label: "Abilify" },
  { value: "Acamprosate", label: "Acamprosate" },
  { value: "Acarbose", label: "Acarbose" },
  { value: "Accutane (Isotretinoin)", label: "Accutane" },
  { value: "Acebutolol", label: "Acebutolol" },
  { value: "Acetaminophen", label: "Acetaminophen" },
  { value: "Acetazolamide", label: "Acetazolamide" },
  { value: "Acetic Acid", label: "Acetic Acid" },
  { value: "Acyclovir", label: "Acyclovir" },
  { value: "Adalimumab", label: "Adalimumab" },
  { value: "Albutein (Albumin)", label: "Albutein" },
  { value: "Albuterol", label: "Albuterol" },
  { value: "Alendronate", label: "Alendronate" },
  { value: "Allopurinol", label: "Allopurinol" },
  { value: "Alprazolam", label: "Alprazolam" },
  { value: "Amiodarone", label: "Amiodarone" },
  { value: "Amlodipine", label: "Amlodipine" },
  { value: "Amoxicillin", label: "Amoxicillin" },
  { value: "Ampicillin", label: "Ampicillin" },
  { value: "Anastrozole", label: "Anastrozole" },
  { value: "Apixaban", label: "Apixaban" },
  { value: "Aripiprazole", label: "Aripiprazole" },
  { value: "Aspirin", label: "Aspirin" },
  { value: "Atenolol", label: "Atenolol" },
  { value: "Atorvastatin", label: "Atorvastatin" },
  { value: "Azathioprine", label: "Azathioprine" },
  { value: "Azithromycin", label: "Azithromycin" },
  { value: "Baclofen", label: "Baclofen" },
  { value: "Benzonatate", label: "Benzonatate" },
  { value: "Bisoprolol", label: "Bisoprolol" },
  { value: "Budesonide", label: "Budesonide" },
  { value: "Buprenorphine", label: "Buprenorphine" },
  { value: "Bupropion", label: "Bupropion" },
  { value: "Buspirone", label: "Buspirone" },
  { value: "Captopril", label: "Captopril" },
  { value: "Carbamazepine", label: "Carbamazepine" },
  { value: "Carvedilol", label: "Carvedilol" },
  { value: "Cefalexin", label: "Cefalexin" },
  { value: "Cefuroxime", label: "Cefuroxime" },
  { value: "Celecoxib", label: "Celecoxib" },
  { value: "Cephalexin", label: "Cephalexin" },
  { value: "Chlorhexidine", label: "Chlorhexidine" },
  { value: "Chlorthalidone", label: "Chlorthalidone" },
  { value: "Ciprofloxacin", label: "Ciprofloxacin" },
  { value: "Citalopram", label: "Citalopram" },
  { value: "Clarithromycin", label: "Clarithromycin" },
  { value: "Clindamycin", label: "Clindamycin" },
  { value: "Clobetasol", label: "Clobetasol" },
  { value: "Clomipramine", label: "Clomipramine" },
  { value: "Clonazepam", label: "Clonazepam" },
  { value: "Clonidine", label: "Clonidine" },
  { value: "Clopidogrel", label: "Clopidogrel" },
  { value: "Clotrimazole", label: "Clotrimazole" },
  { value: "Codeine", label: "Codeine" },
  { value: "Colchicine", label: "Colchicine" },
  { value: "Cyclobenzaprine", label: "Cyclobenzaprine" },
  { value: "Cyclophosphamide", label: "Cyclophosphamide" },
  { value: "Cyclosporine", label: "Cyclosporine" },
  { value: "Dabigatran", label: "Dabigatran" },
  { value: "Dapagliflozin", label: "Dapagliflozin" },
  { value: "Dexamethasone", label: "Dexamethasone" },
  { value: "Diazepam", label: "Diazepam" },
  { value: "Diclofenac", label: "Diclofenac" },
  { value: "Digoxin", label: "Digoxin" },
  { value: "Diltiazem", label: "Diltiazem" },
  { value: "Diphenhydramine", label: "Diphenhydramine" },
  { value: "Dipyridamole", label: "Dipyridamole" },
  { value: "Divalproex", label: "Divalproex" },
  { value: "Donepezil", label: "Donepezil" },
  { value: "Doxazosin", label: "Doxazosin" },
  { value: "Doxepin", label: "Doxepin" },
  { value: "Doxycycline", label: "Doxycycline" },
  { value: "Duloxetine", label: "Duloxetine" },
  { value: "Empagliflozin", label: "Empagliflozin" },
  { value: "Enalapril", label: "Enalapril" },
  { value: "Erythromycin", label: "Erythromycin" },
  { value: "Escitalopram", label: "Escitalopram" },
  { value: "Esomeprazole", label: "Esomeprazole" },
  { value: "Estradiol", label: "Estradiol" },
  { value: "Ethinylestradiol", label: "Ethinylestradiol" },
  { value: "Etodolac", label: "Etodolac" },
  { value: "Exenatide", label: "Exenatide" },
  { value: "Ezetimibe", label: "Ezetimibe" },
  { value: "Famotidine", label: "Famotidine" },
  { value: "Felodipine", label: "Felodipine" },
  { value: "Fenofibrate", label: "Fenofibrate" },
  { value: "Fentanyl", label: "Fentanyl" },
  { value: "Finasteride", label: "Finasteride" },
  { value: "Fluconazole", label: "Fluconazole" },
  { value: "Fluoxetine", label: "Fluoxetine" },
  { value: "Fluticasone", label: "Fluticasone" },
  { value: "Folic Acid", label: "Folic Acid" },
  { value: "Furosemide", label: "Furosemide" },
  { value: "Gabapentin", label: "Gabapentin" },
  { value: "Galantamine", label: "Galantamine" },
  { value: "Gatifloxacin", label: "Gatifloxacin" },
  { value: "Gemfibrozil", label: "Gemfibrozil" },
  { value: "Gentamicin", label: "Gentamicin" },
  { value: "Glibenclamide", label: "Glibenclamide" },
  { value: "Glimepiride", label: "Glimepiride" },
  { value: "Glipizide", label: "Glipizide" },
  { value: "Glyburide", label: "Glyburide" },
  { value: "Hydrochlorothiazide", label: "Hydrochlorothiazide" },
  { value: "Hydrocortisone", label: "Hydrocortisone" },
  { value: "Hydroxychloroquine", label: "Hydroxychloroquine" },
  { value: "Hydroxyzine", label: "Hydroxyzine" },
  { value: "Ibuprofen", label: "Ibuprofen" },
  { value: "Imatinib", label: "Imatinib" },
  { value: "Insulin", label: "Insulin" },
  { value: "Ipratropium", label: "Ipratropium" },
  { value: "Irbesartan", label: "Irbesartan" },
  { value: "Isosorbide", label: "Isosorbide" },
  { value: "Itraconazole", label: "Itraconazole" },
  { value: "Ivermectin", label: "Ivermectin" },
  { value: "Ketoconazole", label: "Ketoconazole" },
  { value: "Labetalol", label: "Labetalol" },
  { value: "Lacosamide", label: "Lacosamide" },
  { value: "Lamotrigine", label: "Lamotrigine" },
  { value: "Lansoprazole", label: "Lansoprazole" },
  { value: "Latanoprost", label: "Latanoprost" },
  { value: "Levetiracetam", label: "Levetiracetam" },
  { value: "Levofloxacin", label: "Levofloxacin" },
  { value: "Levothyroxine", label: "Levothyroxine" },
  { value: "Lisinopril", label: "Lisinopril" },
  { value: "Lithium", label: "Lithium" },
  { value: "Loperamide", label: "Loperamide" },
  { value: "Loratadine", label: "Loratadine" },
  { value: "Lorazepam", label: "Lorazepam" },
  { value: "Losartan", label: "Losartan" },
  { value: "Lovastatin", label: "Lovastatin" },
  { value: "Macitentan", label: "Macitentan" },
  { value: "Magnesium Oxide", label: "Magnesium Oxide" },
  { value: "Meclizine", label: "Meclizine" },
  { value: "Meloxicam", label: "Meloxicam" },
  { value: "Memantine", label: "Memantine" },
  { value: "Metformin", label: "Metformin" },
  { value: "Methadone", label: "Methadone" },
  { value: "Methocarbamol", label: "Methocarbamol" },
  { value: "Methotrexate", label: "Methotrexate" },
  { value: "Methylphenidate", label: "Methylphenidate" },
  { value: "Metoclopramide", label: "Metoclopramide" },
  { value: "Metoprolol", label: "Metoprolol" },
  { value: "Metronidazole", label: "Metronidazole" },
  { value: "Mirtazapine", label: "Mirtazapine" },
  { value: "Misoprostol", label: "Misoprostol" },
  { value: "Modafinil", label: "Modafinil" },
  { value: "Montelukast", label: "Montelukast" },
  { value: "Morphine", label: "Morphine" },
  { value: "Nabumetone", label: "Nabumetone" },
  { value: "Nadolol", label: "Nadolol" },
  { value: "Naloxone", label: "Naloxone" },
  { value: "Naproxen", label: "Naproxen" },
  { value: "Nebivolol", label: "Nebivolol" },
  { value: "Nifedipine", label: "Nifedipine" },
  { value: "Nitroglycerin", label: "Nitroglycerin" },
  { value: "Nortriptyline", label: "Nortriptyline" },
  { value: "Olanzapine", label: "Olanzapine" },
  { value: "Omeprazole", label: "Omeprazole" },
  { value: "Ondansetron", label: "Ondansetron" },
  { value: "Oseltamivir", label: "Oseltamivir" },
  { value: "Oxcarbazepine", label: "Oxcarbazepine" },
  { value: "Oxycodone", label: "Oxycodone" },
  { value: "Oxytocin", label: "Oxytocin" },
  { value: "Pantoprazole", label: "Pantoprazole" },
  { value: "Paracetamol", label: "Paracetamol" },
  { value: "Penicillin", label: "Penicillin" },
  { value: "Phenobarbital", label: "Phenobarbital" },
  { value: "Phenytoin", label: "Phenytoin" },
  { value: "Pioglitazone", label: "Pioglitazone" },
  { value: "Pregabalin", label: "Pregabalin" },
  { value: "Prilosec", label: "Prilosec" },
  { value: "Prochlorperazine", label: "Prochlorperazine" },
  { value: "Promethazine", label: "Promethazine" },
  { value: "Propranolol", label: "Propranolol" },
  { value: "Quetiapine", label: "Quetiapine" },
  { value: "Rabeprazole", label: "Rabeprazole" },
  { value: "Ramipril", label: "Ramipril" },
  { value: "Ranitidine", label: "Ranitidine" },
  { value: "Rifaximin", label: "Rifaximin" },
  { value: "Risperidone", label: "Risperidone" },
  { value: "Rivaroxaban", label: "Rivaroxaban" },
  { value: "Rosuvastatin", label: "Rosuvastatin" },
  { value: "Sertraline", label: "Sertraline" },
  { value: "Sildenafil", label: "Sildenafil" },
  { value: "Simvastatin", label: "Simvastatin" },
  { value: "Sitagliptin", label: "Sitagliptin" },
  { value: "Sodium Valproate", label: "Sodium Valproate" },
  { value: "Solifenacin", label: "Solifenacin" },
  { value: "Spironolactone", label: "Spironolactone" },
  { value: "Sucralfate", label: "Sucralfate" },
  { value: "Sulfamethoxazole", label: "Sulfamethoxazole" },
  { value: "Sumatriptan", label: "Sumatriptan" },
  { value: "Tacrolimus", label: "Tacrolimus" },
  { value: "Tadalafil", label: "Tadalafil" },
  { value: "Tamoxifen", label: "Tamoxifen" },
  { value: "Tamsulosin", label: "Tamsulosin" },
  { value: "Telmisartan", label: "Telmisartan" },
  { value: "Terbinafine", label: "Terbinafine" },
  { value: "Tetracycline", label: "Tetracycline" },
  { value: "Thyroxine", label: "Thyroxine" },
  { value: "Timolol", label: "Timolol" },
  { value: "Tiotropium", label: "Tiotropium" },
  { value: "Topiramate", label: "Topiramate" },
  { value: "Torsemide", label: "Torsemide" },
  { value: "Tramadol", label: "Tramadol" },
  { value: "Trazodone", label: "Trazodone" },
  { value: "Triamcinolone", label: "Triamcinolone" },
  { value: "Triamterene", label: "Triamterene" },
  { value: "Triazolam", label: "Triazolam" },
  { value: "Triclabendazole", label: "Triclabendazole" },
  { value: "Triclosan", label: "Triclosan" },
  { value: "Trifluoperazine", label: "Trifluoperazine" },
  { value: "Trifluridine", label: "Trifluridine" },
  { value: "Triglide (Fenofibrate)", label: "Triglide" },
  { value: "Trimethoprim", label: "Trimethoprim" },
  { value: "Trimetrexate", label: "Trimetrexate" },
  { value: "Triptorelin", label: "Triptorelin" },
  { value: "Trovafloxacin", label: "Trovafloxacin" },
  { value: "Trospium", label: "Trospium" },
  { value: "Truvada (Emtricitabine/Tenofovir)", label: "Truvada" },
  { value: "Tubocurarine", label: "Tubocurarine" },
  { value: "Tucatinib", label: "Tucatinib" },
  { value: "Tulobuterol", label: "Tulobuterol" },
  { value: "Tumor Necrosis Factor Blockers", label: "Tumor Necrosis Factor Blockers" },
  { value: "Tums (Calcium Carbonate)", label: "Tums" },
  { value: "Turox (Etodolac)", label: "Turox" },
  { value: "Tygacil (Tigecycline)", label: "Tygacil" },
  { value: "Tylenol (Acetaminophen)", label: "Tylenol" },
  { value: "Tyrosine Kinase Inhibitors", label: "Tyrosine Kinase Inhibitors" },
  { value: "Ubidecarenone", label: "Ubidecarenone" },
  { value: "Ubrogepant", label: "Ubrogepant" },
  { value: "Udenafil", label: "Udenafil" },
  { value: "Uloric (Febuxostat)", label: "Uloric" },
  { value: "Umeclidinium", label: "Umeclidinium" },
  { value: "Unasyn (Ampicillin and Sulbactam)", label: "Unasyn" },
  { value: "Uptravi (Selexipag)", label: "Uptravi" },
  { value: "Urea", label: "Urea" },
  { value: "Urispas (Flavoxate)", label: "Urispas" },
  { value: "Ursodiol", label: "Ursodiol" },
  { value: "Ustekinumab", label: "Ustekinumab" },
  { value: "Vabomere (Meropenem and Vaborbactam)", label: "Vabomere" },
  { value: "Valacyclovir", label: "Valacyclovir" },
  { value: "Valdecoxib", label: "Valdecoxib" },
  { value: "Valganciclovir", label: "Valganciclovir" },
  { value: "Valium (Diazepam)", label: "Valium" },
  { value: "Valsartan", label: "Valsartan" },
  { value: "Vancomycin", label: "Vancomycin" },
  { value: "Vardenafil", label: "Vardenafil" },
  { value: "Varenicline", label: "Varenicline" },
  { value: "Vascepa (Icosapent Ethyl)", label: "Vascepa" },
  { value: "Vedolizumab", label: "Vedolizumab" },
  { value: "Venlafaxine", label: "Venlafaxine" },
  { value: "Verapamil", label: "Verapamil" },
  { value: "Vericiguat", label: "Vericiguat" },
  { value: "Verteporfin", label: "Verteporfin" },
  { value: "Vesicare (Solifenacin)", label: "Vesicare" },
  { value: "Viagra (Sildenafil)", label: "Viagra" },
  { value: "Vibativ (Telavancin)", label: "Vibativ" },
  { value: "Vicodin (Hydrocodone and Acetaminophen)", label: "Vicodin" },
  { value: "Victoza (Liraglutide)", label: "Victoza" },
  { value: "Vidarabine", label: "Vidarabine" },
  { value: "Vigabatrin", label: "Vigabatrin" },
  { value: "Vilanterol", label: "Vilanterol" },
  { value: "Vildagliptin", label: "Vildagliptin" },
  { value: "Vinblastine", label: "Vinblastine" },
  { value: "Vincristine", label: "Vincristine" },
  { value: "Vinorelbine", label: "Vinorelbine" },
  { value: "Viokace (Pancrelipase)", label: "Viokace" },
  { value: "Vioxx (Rofecoxib)", label: "Vioxx" },
  { value: "Viramune (Nevirapine)", label: "Viramune" },
  { value: "Viread (Tenofovir)", label: "Viread" },
  { value: "Visanne (Dienogest)", label: "Visanne" },
  { value: "Visbiome (Probiotic)", label: "Visbiome" },
  { value: "Vismodegib", label: "Vismodegib" },
  { value: "Vistide (Cidofovir)", label: "Vistide" },
  { value: "Vitamin B12 (Cyanocobalamin)", label: "Vitamin B12" },
  { value: "Vitamin D", label: "Vitamin D" },
  { value: "Vitamin E", label: "Vitamin E" },
  { value: "Vitamin K", label: "Vitamin K" },
  { value: "Vivitrol (Naltrexone)", label: "Vivitrol" },
  { value: "Voglibose", label: "Voglibose" },
  { value: "Voriconazole", label: "Voriconazole" },
  { value: "Vortioxetine", label: "Vortioxetine" },
  { value: "Vosevi (Sofosbuvir, Velpatasvir, and Voxilaprevir)", label: "Vosevi" },
  { value: "Vraylar (Cariprazine)", label: "Vraylar" },
  { value: "Vytorin (Ezetimibe and Simvastatin)", label: "Vytorin" },
  { value: "Vyvanse (Lisdexamfetamine)", label: "Vyvanse" },
  { value: "Warfarin", label: "Warfarin" },
  { value: "Welchol (Colesevelam)", label: "Welchol" },
  { value: "Wellbutrin (Bupropion)", label: "Wellbutrin" },
  { value: "Xanax (Alprazolam)", label: "Xanax" },
  { value: "Xarelto (Rivaroxaban)", label: "Xarelto" },
  { value: "Xeljanz (Tofacitinib)", label: "Xeljanz" },
  { value: "Xeloda (Capecitabine)", label: "Xeloda" },
  { value: "Xenazine (Tetrabenazine)", label: "Xenazine" },
  { value: "Xenical (Orlistat)", label: "Xenical" },
  { value: "Xgeva (Denosumab)", label: "Xgeva" },
  { value: "Xifaxan (Rifaximin)", label: "Xifaxan" },
  { value: "Xigduo XR (Dapagliflozin and Metformin)", label: "Xigduo XR" },
  { value: "Xofigo (Radium Ra 223 Dichloride)", label: "Xofigo" },
  { value: "Xolair (Omalizumab)", label: "Xolair" },
  { value: "Xtandi (Enzalutamide)", label: "Xtandi" },
  { value: "Xylocaine (Lidocaine)", label: "Xylocaine" },
  { value: "Xyzal (Levocetirizine)", label: "Xyzal" },
  { value: "Yasmin (Drospirenone and Ethinyl Estradiol)", label: "Yasmin" },
  { value: "Yaz (Drospirenone and Ethinyl Estradiol)", label: "Yaz" },
  { value: "Yervoy (Ipilimumab)", label: "Yervoy" },
  { value: "Yohimbine", label: "Yohimbine" },
  { value: "Yonsa (Abiraterone)", label: "Yonsa" },
  { value: "Zafirlukast", label: "Zafirlukast" },
  { value: "Zalcitabine", label: "Zalcitabine" },
  { value: "Zaleplon", label: "Zaleplon" },
  { value: "Zanamivir", label: "Zanamivir" },
  { value: "Zantac (Ranitidine)", label: "Zantac" },
  { value: "Zarontin (Ethosuximide)", label: "Zarontin" },
  { value: "Zebeta (Bisoprolol)", label: "Zebeta" },
  { value: "Zelnorm (Tegaserod)", label: "Zelnorm" },
  { value: "Zemaira (Alpha1-Proteinase Inhibitor)", label: "Zemaira" },
  { value: "Zenapax (Daclizumab)", label: "Zenapax" },
  { value: "Zepatier (Elbasvir and Grazoprevir)", label: "Zepatier" },
  { value: "Zerit (Stavudine)", label: "Zerit" },
  { value: "Zestril (Lisinopril)", label: "Zestril" },
  { value: "Zetia (Ezetimibe)", label: "Zetia" },
  { value: "Ziagen (Abacavir)", label: "Ziagen" },
  { value: "Ziconotide", label: "Ziconotide" },
  { value: "Zidovudine", label: "Zidovudine" },
  { value: "Zileuton", label: "Zileuton" },
  { value: "Ziprasidone", label: "Ziprasidone" },
  { value: "Zithromax (Azithromycin)", label: "Zithromax" },
  { value: "Zocor (Simvastatin)", label: "Zocor" },
  { value: "Zofran (Ondansetron)", label: "Zofran" },
  { value: "Zoladex (Goserelin)", label: "Zoladex" },
  { value: "Zoledronic Acid", label: "Zoledronic Acid" },
  { value: "Zolmitriptan", label: "Zolmitriptan" },
  { value: "Zolpidem", label: "Zolpidem" },
  { value: "Zometa (Zoledronic Acid)", label: "Zometa" },
  { value: "Zomig (Zolmitriptan)", label: "Zomig" },
  { value: "Zonegran (Zonisamide)", label: "Zonegran" },
  { value: "Zonisamide", label: "Zonisamide" },
  { value: "Zostavax (Shingles Vaccine)", label: "Zostavax" },
  { value: "Zosyn (Piperacillin and Tazobactam)", label: "Zosyn" },
  { value: "Zovirax (Acyclovir)", label: "Zovirax" },
  { value: "Zubsolv (Buprenorphine and Naloxone)", label: "Zubsolv" },
  { value: "Zurampic (Lesinurad)", label: "Zurampic" },
  { value: "Zyban (Bupropion)", label: "Zyban" },
  { value: "Zyclara (Imiquimod)", label: "Zyclara" },
  { value: "Zydelig (Idelalisib)", label: "Zydelig" },
  { value: "Zyflo (Zileuton)", label: "Zyflo" },
  { value: "Zykadia (Ceritinib)", label: "Zykadia" },
  { value: "Zylet (Loteprednol and Tobramycin)", label: "Zylet" },
  { value: "Zyloprim (Allopurinol)", label: "Zyloprim" },
  { value: "Zymar (Gatifloxacin)", label: "Zymar" },
  { value: "Zyprexa (Olanzapine)", label: "Zyprexa" },
  { value: "Zyrtec (Cetirizine)", label: "Zyrtec" },
  { value: "Zytiga (Abiraterone)", label: "Zytiga" },
  { value: "Zyvox (Linezolid)", label: "Zyvox" },
];

export const dosageUnits = [
  { value: "mg", label: "Milligrams (mg)" },
  { value: "g", label: "Grams (g)" },
  { value: "ml", label: "Milliliters (ml)" },
  { value: "units", label: "Units" },
  { value: "mcg", label: "Micrograms (mcg)" },
  { value: "IU", label: "International Units (IU)" },
  { value: "l", label: "Liters (l)" },
  { value: "dl", label: "Deciliters (dl)" },
  { value: "cl", label: "Centiliters (cl)" },
  { value: "mmol", label: "Millimoles (mmol)" },
  { value: "nmol", label: "Nanomoles (nmol)" },
  { value: "mEq", label: "Milliequivalents (mEq)" },
  { value: "Percent %", label: "Percent %" },
];

export const dosageFrequency = [
  { value: "qd", label: "Once a day" },
  { value: "bid", label: "Twice a day" },
  { value: "tid", label: "Three times a day" },
  { value: "qid", label: "Four times a day" },
  { value: "qod", label: "Every other day" },
  { value: "weekly", label: "Once a week" },
  { value: "biweekly", label: "Twice a week" },
  { value: "monthly", label: "Once a month" },
  { value: "prn", label: "As needed" },
  { value: "qam", label: "Every morning" },
  { value: "qpm", label: "Every evening" },
  { value: "qhs", label: "At bedtime" },
  { value: "stat", label: "Immediately" },
  { value: "ac", label: "Before meals" },
  { value: "pc", label: "After meals" },
  { value: "q2h", label: "Every 2 hours" },
  { value: "q3h", label: "Every 3 hours" },
  { value: "q4h", label: "Every 4 hours" },
  { value: "q6h", label: "Every 6 hours" },
  { value: "q8h", label: "Every 8 hours" },
  { value: "q12h", label: "Every 12 hours" },
  { value: "q24h", label: "Every 24 hours" },
];

//IN GB
export const allotedPatientStoragesInGb = {
  FREE: 0.003,
  PREMIUM_1: 10,
  PREMIUM_2: 100,
};

export const accessCodeValidTimeObj = {
  MINUTE_30: 1800,
  HOUR_1: 3600,
  HOUR_12: 43200,
  DAY_1: 86400,
  WEEK_1: 604800,
};
